[package]
name = "platform-game-experiment"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
gfx = "0.17"
gfx_device_gl = "0.15"
gfx_window_glutin = "0.23"
glutin = "0.15"
